site_name: Aqueduct Experiment Control Software
site_author: Riverlane Ltd.
site_url: https://aqueducthub.github.io/aqueductcore/
repo_name: aqueducthub/aqueductcore
docs_dir: "docs"
theme:
  name: material
  language: en
  icon:
    logo: material/contacts
  favicon: images/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: teal
      accent: red

  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - toc:
      permalink: true
      toc_depth: 2

plugins:
  - search
  - mike
  - mkdocstrings:
      handlers:
        python:
          paths: [pyaqueduct]

nav:
  - "index.md"
  - "cli.md"
  - "setup.md"
  - "getting-started.md"
  - "Python Client": "https://aqueducthub.github.io/pyaqueduct/"

copyright: Copyright &copy; 2023 - 2024 Riverlane Ltd.
