version: '3'
services:
  aqueduct:
    platform: linux/amd64
    image: aqueducthub/aqueductcore:latest
    restart: always
    depends_on:
      - postgres
    environment:
      EXPERIMENTS_DIR_PATH: /tmp/aqueduct_experiments
      EXTENSIONS_DIR_PATH: /workspace/plugins
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: aqueduct
    volumes:
      - ${EXPERIMENTS_DIR}:/tmp/aqueduct_experiments
      - type: bind
        source: ${EXTENSIONS_DIR}
        target: /workspace/extensions
    ports:
      - 80:8000

  postgres:
    platform: linux/amd64
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=aqueduct
    expose:
      - 5432
