# Service layer constants

MAX_EXPERRIMENTS_PER_REQUEST = 500
MAX_TAGS_PER_REQUEST = 500

MAX_EXPERIMENT_TITLE_LENGTH = 256
MAX_EXPERIMENT_DESCRIPTION_LENGTH = 5000
MAX_TAG_LENGTH = 64
MAX_EXPERIMENT_TAGS = 64

MAX_FILTER_TITLE_LENGTH = 8
MAX_SHOULD_INCLUDE_TAGS_LENGTH = 6
MAX_TAGS_ALLOWED_IN_FILTER = 10
