"""update with created_by column

Revision ID: 6d5f957d035c
Revises: a31025856641
Create Date: 2024-09-12 15:20:42.847502

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d5f957d035c"
down_revision: Union[str, None] = "a31025856641"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    bind = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("created_by", sa.Uuid(), nullable=True))
    bind.execute(
        text(
            "UPDATE task \
            SET created_by = '00000000-0000-0000-0000-000000000000'"
        )
    )
    op.alter_column("task", "created_by", nullable=False)
    op.create_foreign_key(None, "task", "user", ["created_by"], ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_column("task", "status")
    op.drop_column("task", "created_by")
    op.create_unique_constraint("tag_key_key", "tag", ["key"])
    op.create_table(
        "celery_tasksetmeta",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("taskset_id", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.Column("result", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column("date_done", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="celery_tasksetmeta_pkey"),
        sa.UniqueConstraint("taskset_id", name="celery_tasksetmeta_taskset_id_key"),
    )
    op.create_table(
        "celery_taskmeta",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("result", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column("date_done", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("traceback", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.Column("args", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column("kwargs", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column("worker", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.Column("retries", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("queue", sa.VARCHAR(length=155), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="celery_taskmeta_pkey"),
        sa.UniqueConstraint("task_id", name="celery_taskmeta_task_id_key"),
    )
    # ### end Alembic commands ###
