"""Rename task_id to uuid

Revision ID: c12374978a12
Revises: 6d5f957d035c
Create Date: 2024-10-11 11:44:29.159937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12374978a12'
down_revision: Union[str, None] = '6d5f957d035c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'task_id', new_column_name='uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
