/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

const documents = {
    "\n  mutation addTagToExperiment($experimentId: UUID!, $tag: String!) {\n    addTagToExperiment(experimentTagInput: { experimentId: $experimentId, tag: $tag }) {\n      id\n      tags\n    }\n  }\n": types.AddTagToExperimentDocument,
    "\n  mutation removeTagFromExperiment($experimentId: UUID!, $tag: String!) {\n    removeTagFromExperiment(experimentTagInput: { experimentId: $experimentId, tag: $tag }) {\n      id\n      tags\n    }\n  }\n": types.RemoveTagFromExperimentDocument,
    "\n  mutation updateExperimentName(\n    $experimentId: UUID!\n    $experimentUpdateInput: ExperimentUpdateInput!\n  ) {\n    updateExperiment(experimentId: $experimentId, experimentUpdateInput: $experimentUpdateInput) {\n      id\n      title\n      description\n      alias\n    }\n  }\n": types.UpdateExperimentNameDocument,
    "\n  query getAllExperiments($offset: Int!, $limit: Int!, $filters: ExperimentFiltersInput) {\n    experiments(offset: $offset, limit: $limit, filters: $filters) {\n      experimentsData {\n        id\n        alias\n        title\n        description\n        tags\n        createdAt\n      }\n      totalExperimentsCount\n    }\n  }\n": types.GetAllExperimentsDocument,
    "\n  query getAllTags {\n    tags {\n      tagsData\n    }\n  }\n": types.GetAllTagsDocument,
    "\n  query getExperimentById($experimentIdentifier: ExperimentIdentifierInput!) {\n    experiment(experimentIdentifier: $experimentIdentifier) {\n      id\n      title\n      description\n      tags\n      alias\n      createdAt\n      files {\n        name\n        path\n        modifiedAt\n      }\n    }\n  }\n": types.GetExperimentByIdDocument,
    "\n  query getExperimentFilesById($experimentIdentifier: ExperimentIdentifierInput!) {\n    experiment(experimentIdentifier: $experimentIdentifier) {\n      files {\n        name\n        path\n        modifiedAt\n      }\n    }\n  }\n": types.GetExperimentFilesByIdDocument,
};

export function graphql(source: "\n  mutation addTagToExperiment($experimentId: UUID!, $tag: String!) {\n    addTagToExperiment(experimentTagInput: { experimentId: $experimentId, tag: $tag }) {\n      id\n      tags\n    }\n  }\n"): (typeof documents)["\n  mutation addTagToExperiment($experimentId: UUID!, $tag: String!) {\n    addTagToExperiment(experimentTagInput: { experimentId: $experimentId, tag: $tag }) {\n      id\n      tags\n    }\n  }\n"];
export function graphql(source: "\n  mutation removeTagFromExperiment($experimentId: UUID!, $tag: String!) {\n    removeTagFromExperiment(experimentTagInput: { experimentId: $experimentId, tag: $tag }) {\n      id\n      tags\n    }\n  }\n"): (typeof documents)["\n  mutation removeTagFromExperiment($experimentId: UUID!, $tag: String!) {\n    removeTagFromExperiment(experimentTagInput: { experimentId: $experimentId, tag: $tag }) {\n      id\n      tags\n    }\n  }\n"];
export function graphql(source: "\n  mutation updateExperimentName(\n    $experimentId: UUID!\n    $experimentUpdateInput: ExperimentUpdateInput!\n  ) {\n    updateExperiment(experimentId: $experimentId, experimentUpdateInput: $experimentUpdateInput) {\n      id\n      title\n      description\n      alias\n    }\n  }\n"): (typeof documents)["\n  mutation updateExperimentName(\n    $experimentId: UUID!\n    $experimentUpdateInput: ExperimentUpdateInput!\n  ) {\n    updateExperiment(experimentId: $experimentId, experimentUpdateInput: $experimentUpdateInput) {\n      id\n      title\n      description\n      alias\n    }\n  }\n"];
export function graphql(source: "\n  query getAllExperiments($offset: Int!, $limit: Int!, $filters: ExperimentFiltersInput) {\n    experiments(offset: $offset, limit: $limit, filters: $filters) {\n      experimentsData {\n        id\n        alias\n        title\n        description\n        tags\n        createdAt\n      }\n      totalExperimentsCount\n    }\n  }\n"): (typeof documents)["\n  query getAllExperiments($offset: Int!, $limit: Int!, $filters: ExperimentFiltersInput) {\n    experiments(offset: $offset, limit: $limit, filters: $filters) {\n      experimentsData {\n        id\n        alias\n        title\n        description\n        tags\n        createdAt\n      }\n      totalExperimentsCount\n    }\n  }\n"];
export function graphql(source: "\n  query getAllTags {\n    tags {\n      tagsData\n    }\n  }\n"): (typeof documents)["\n  query getAllTags {\n    tags {\n      tagsData\n    }\n  }\n"];
export function graphql(source: "\n  query getExperimentById($experimentIdentifier: ExperimentIdentifierInput!) {\n    experiment(experimentIdentifier: $experimentIdentifier) {\n      id\n      title\n      description\n      tags\n      alias\n      createdAt\n      files {\n        name\n        path\n        modifiedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query getExperimentById($experimentIdentifier: ExperimentIdentifierInput!) {\n    experiment(experimentIdentifier: $experimentIdentifier) {\n      id\n      title\n      description\n      tags\n      alias\n      createdAt\n      files {\n        name\n        path\n        modifiedAt\n      }\n    }\n  }\n"];
export function graphql(source: "\n  query getExperimentFilesById($experimentIdentifier: ExperimentIdentifierInput!) {\n    experiment(experimentIdentifier: $experimentIdentifier) {\n      files {\n        name\n        path\n        modifiedAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query getExperimentFilesById($experimentIdentifier: ExperimentIdentifierInput!) {\n    experiment(experimentIdentifier: $experimentIdentifier) {\n      files {\n        name\n        path\n        modifiedAt\n      }\n    }\n  }\n"];

export function graphql(source: string): unknown;
export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;