---
version: "3.8"
services:
  aqueductcore:
    build:
      context: ../..
      dockerfile: containers/dev/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    user: dev_user
    container_name: aqueductcore
    platform: linux/amd64
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - ../../aqueductcore/frontend/envs/.env.dev
      - ../../envs/.env.dev
    volumes:
      # Use a named volume for the source code
      - ../../:/workspace
      - ${HOME}/.ssh:/home/dev_user/.ssh

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    platform: linux/amd64
    environment:
      - POSTGRES_USER=aqueductcore
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aqueductcore_dev
    expose:
      - 5432

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
