---
version: "3.8"
services:
  aqueductcore:
    build:
      context: ../..
      dockerfile: containers/dev/Dockerfile
    depends_on:
      - postgres
      - rabbit-with-celery
    user: dev_user
    container_name: aqueductcore
    platform: linux/amd64
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - ../../aqueductcore/frontend/envs/.env.dev
      - ../../envs/.env.dev
    volumes:
      # Use a named volume for the source code
      - ../../:/workspace
      - ${HOME}/.ssh:/home/dev_user/.ssh

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    platform: linux/amd64
    environment:
      - POSTGRES_USER=aqueductcore
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aqueductcore_dev
    expose:
      - 5432

  rabbit-with-celery:
    build:
      context: ../..
      dockerfile: poc/Dockerfile
    container_name: rabbit-with-celery-container
    platform: linux/amd64
    env_file:
      - ../../aqueductcore/frontend/envs/.env.dev
      - ../../envs/.env.dev
    environment:
      HOST: "localhost"
    volumes:
      # Use a named volume for the source code
      - ../../:/workspace
    expose:
      # flower
      - 5555
      # message queue
      - 5672
    ports:
      - "5555:5555"
