name: Development Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build and Push Dev Container
        run: ci/build_docker_image.sh -i aqueductcore-dev -p true -t ${{ github.sha }}

      - name: Build and Push Dev Container SSH Server for Azure
        run: ci/build_docker_image.sh -i aqueductcore-dev-azure -p true -t ${{ github.sha }} -d containers/release-azure/Dockerfile
