name: Docs latest and released versions

on:
  push:
    branches:
      - "v*.*"
      - main

jobs:
  build_docs:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_REPO_PAT }}
          fetch-depth: 0
          submodules: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.5.1

      - name: Install packages
        run: |
          poetry install

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build docs
        run: |
          poetry run mike deploy --push ${{ steps.extract_branch.outputs.branch }}

      - name: Create all versions directory
        run: |
          mkdir -p site \
          && git archive gh-pages | tar x -C site

      - name: Form authentication structure for Azure web app
        run: |
          cp -r ci/staticwebapp.config.json site

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_SAND_0B0E2A903 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "site" # App source code path
