name: Generate license report of dependencies

on:
  workflow_dispatch:

jobs:
  update_variable:
    runs-on: ubuntu-latest
    steps:
      - name: "✏️ Generate release changelog"
        id: generate_changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
      - name: "Write changelog to file"
        run: echo "${{ steps.generate_changelog.outputs.changelog }}" > changelog.txt
      - name: "Print output"
        run: cat changelog.txt
