name: Generate license report of dependencies.

on:
  workflow_dispatch:

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current release version and calculate next patch version
        id: next_version
        run: |
          git fetch --tags
          CURRENT_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          NEXT_VERSION=$(echo $CURRENT_VERSION | awk -F. '{ printf "%d.%d.%d", $1, $2, $3+1 }')
          echo "version=$NEXT_VERSION"
          echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Print the above generated version
        run: |
          echo ${{ steps.next_version.outputs.version }}
