name: License report of packages used

on:
  pull_request:
    branches: [feat-*]
  workflow_dispatch:

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_GITHUB_REPO_PAT }}
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.5.1

      - name: Install packages
        run: poetry install

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --cwd aqueductcore/frontend

      - name: Create a markdown file with contents
        id: sets-licenses
        run: |
          chmod +x ci/generate_license_report.sh
          ci/generate_license_report.sh
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: licenses.html
