name: Generate license report of dependencies

on:
  workflow_dispatch:

jobs:
  update_variable:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: "✏️ Generate release changelog"
        id: generate_changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
      - name: "Print output"
        run: |
          echo ${{ steps.generate_changelog.outputs.changelog }}
