name: Generate license report of dependencies

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Allow automated release for Aqueduct Core?'
        type: choice
        required: true
        default: 'true'
        options:
          - true
          - false


jobs:
  update_variable:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Environment Variable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/AqueductHub/aqueductcore/environments/automated-release/variables/ALLOW_AUTOMATED_RELEASE \
          -d '{"name":"ALLOW_AUTOMATED_RELEASE","value":"${{ github.event.inputs.debug_mode }}"}'
