name: Release Aqueductcore

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Aqueduct Version"
        required: true
        type: string
        default: "MAJOR.MINOR.PATCH"
  workflow_call:
    inputs:
      version:
        description: "Aqueduct Version"
        required: true
        type: string
        default: "MAJOR.MINOR.PATCH"

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build Release Images
        run: ci/build_docker_image.sh -i aqueductcore -p true -t ${{ inputs.version }}

      - name: Build final archived file
        run: |
          cp scripts/release/docker-compose.yaml ./build \
          && cp scripts/release/install.sh ./build \
          && cp scripts/release/uninstall.sh ./build

          cd build && tar -cvzf aqueduct_v${{ inputs.version }}.tar.gz \
          aqueductcore.tar \
          docker-compose.yaml \
          install.sh \
          uninstall.sh

      - name: Create changelog
        run: |
          ci/create_changelog.sh -o current_changes.md

      - name: Create release and upload artifacts
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ inputs.version }}
          name: "${{ inputs.version }}"
          allowUpdates: true
          artifacts: "build/aqueduct_v${{ inputs.version }}.tar.gz"
          generateReleaseNotes: false
          bodyFile: current_changes.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md file.
        run: |
          cat current_changes.md | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add release ${{ inputs.version }} to CHANGELOG.md file."
          file_pattern: "CHANGELOG.md"
